#!/usr/bin/env python3
"""
OpenSSL Definition File Generator - Python replacement for mkdef.pl

Generates linker version scripts suitable for the given platform from ordinals files.
"""

import argparse
import os
import re
import sys
from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple


class DefinitionGenerator:
    """Generates linker definition files from ordinals."""

    def __init__(self):
        self.name: Optional[str] = None
        self.ordinals_file: Optional[str] = None
        self.version: Optional[str] = None
        self.os: Optional[str] = None
        self.type = 'lib'
        self.verbose = False
        self.ctest = False
        self.debug = False
        self.case_insensitive = False

    def parse_ordinals_file(self, filename: str) -> Dict[str, List[Tuple[str, str, str]]]:
        """Parse an ordinals file and return symbol information."""
        symbols = {}

        try:
            with open(filename, 'r') as f:
                current_section = None

                for line_num, line in enumerate(f, 1):
                    line = line.strip()

                    if not line or line.startswith('#'):
                        continue

                    # Parse section headers
                    if line.startswith('[') and line.endswith(']'):
                        current_section = line[1:-1]
                        if current_section not in symbols:
                            symbols[current_section] = []
                        continue

                    # Parse symbol definitions
                    if current_section and ':' in line:
                        parts = line.split(':')
                        if len(parts) >= 3:
                            symbol_name = parts[0].strip()
                            ordinal = parts[1].strip()
                            version = parts[2].strip() if len(parts) > 2 else ""

                            symbols[current_section].append((symbol_name, ordinal, version))

        except FileNotFoundError:
            print(f"Error: Ordinals file '{filename}' not found", file=sys.stderr)
            return {}

        return symbols

    def generate_version_script(self, symbols: Dict[str, List[Tuple[str, str, str]]],
                               output_file: str) -> None:
        """Generate a version script for GNU ld."""
        with open(output_file, 'w') as f:
            f.write(f"# Generated version script for {self.name}\n")
            f.write("# Do not edit manually - generated by mkdef.py\n\n")

            f.write("{\n")
            f.write("    global:\n")

            # Collect all symbols
            all_symbols = []
            for section_symbols in symbols.values():
                all_symbols.extend(section_symbols)

            # Sort by ordinal
            all_symbols.sort(key=lambda x: int(x[1]) if x[1].isdigit() else 0)

            # Write global symbols
            for symbol_name, ordinal, version in all_symbols:
                f.write(f"        {symbol_name};\n")

            f.write("\n    local:\n")
            f.write("        *;\n")
            f.write("};\n")

        if self.verbose:
            print(f"Generated version script: {output_file}")

    def generate_def_file(self, symbols: Dict[str, List[Tuple[str, str, str]]],
                         output_file: str) -> None:
        """Generate a .def file for Windows."""
        with open(output_file, 'w') as f:
            f.write(f"; Generated definition file for {self.name}\n")
            f.write("; Do not edit manually - generated by mkdef.py\n\n")

            f.write("LIBRARY {}\n".format(self.name.upper()))
            f.write("EXPORTS\n")

            # Collect all symbols
            all_symbols = []
            for section_symbols in symbols.values():
                all_symbols.extend(section_symbols)

            # Sort by ordinal
            all_symbols.sort(key=lambda x: int(x[1]) if x[1].isdigit() else 0)

            # Write exports
            for symbol_name, ordinal, version in all_symbols:
                if ordinal.isdigit():
                    f.write(f"    {symbol_name} @{ordinal}\n")
                else:
                    f.write(f"    {symbol_name}\n")

        if self.verbose:
            print(f"Generated definition file: {output_file}")

    def generate_map_file(self, symbols: Dict[str, List[Tuple[str, str, str]]],
                         output_file: str) -> None:
        """Generate a map file for macOS."""
        with open(output_file, 'w') as f:
            f.write(f"# Generated map file for {self.name}\n")
            f.write("# Do not edit manually - generated by mkdef.py\n\n")

            # Collect all symbols
            all_symbols = []
            for section_symbols in symbols.values():
                all_symbols.extend(section_symbols)

            # Sort by ordinal
            all_symbols.sort(key=lambda x: int(x[1]) if x[1].isdigit() else 0)

            # Write symbols
            for symbol_name, ordinal, version in all_symbols:
                f.write(f"_{symbol_name}\n")

        if self.verbose:
            print(f"Generated map file: {output_file}")

    def run(self, args: List[str]) -> int:
        """Main execution method."""
        parser = argparse.ArgumentParser(description='Generate linker definition files')
        parser.add_argument('--name', type=str, help='Internal library/module name')
        parser.add_argument('--ordinals', type=str, help='Ordinals file to use')
        parser.add_argument('--version', type=str, help='Version to use for the library')
        parser.add_argument('--OS', type=str, help='Operating system family')
        parser.add_argument('--type', type=str, default='lib', choices=['lib', 'dso'],
                          help='Type (lib or dso)')
        parser.add_argument('--ctest', action='store_true', help='Generate for ctest')
        parser.add_argument('--verbose', action='store_true', help='Verbose output')
        parser.add_argument('--case-insensitive', action='store_true',
                          help='Case insensitive names (for VMS)')
        parser.add_argument('output_file', nargs='?', help='Output file')

        parsed_args = parser.parse_args(args)

        self.name = parsed_args.name
        self.ordinals_file = parsed_args.ordinals
        self.version = parsed_args.version
        self.os = parsed_args.OS or self._detect_os()
        self.type = parsed_args.type
        self.verbose = parsed_args.verbose
        self.ctest = parsed_args.ctest
        self.case_insensitive = parsed_args.case_insensitive

        if not self.ordinals_file:
            print("Error: --ordinals file must be specified", file=sys.stderr)
            return 1

        if not self.name:
            print("Error: --name must be specified", file=sys.stderr)
            return 1

        # Parse ordinals file
        symbols = self.parse_ordinals_file(self.ordinals_file)
        if not symbols:
            return 1

        # Determine output file
        output_file = parsed_args.output_file
        if not output_file:
            if self.os == 'linux' or self.os == 'freebsd' or self.os == 'solaris':
                output_file = f"{self.name}.ld"
            elif self.os == 'windows':
                output_file = f"{self.name}.def"
            elif self.os == 'darwin':
                output_file = f"{self.name}.map"
            else:
                output_file = f"{self.name}.ld"

        # Generate appropriate file based on OS
        if self.os == 'windows':
            self.generate_def_file(symbols, output_file)
        elif self.os == 'darwin':
            self.generate_map_file(symbols, output_file)
        else:
            self.generate_version_script(symbols, output_file)

        return 0

    def _detect_os(self) -> str:
        """Detect the operating system."""
        system = sys.platform.lower()
        if system.startswith('linux'):
            return 'linux'
        elif system.startswith('darwin'):
            return 'darwin'
        elif system.startswith('win'):
            return 'windows'
        elif 'freebsd' in system:
            return 'freebsd'
        elif 'solaris' in system:
            return 'solaris'
        else:
            return 'linux'  # default


def main():
    """Main entry point."""
    generator = DefinitionGenerator()
    sys.exit(generator.run(sys.argv[1:]))


if __name__ == '__main__':
    main()