name: Basic OpenSSL Build

on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

jobs:
  basic-build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout OpenSSL
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      
      - name: Install Conan
        run: |
          pip install conan>=2.0
          conan --version
      
      - name: Create Conan Profile
        run: |
          conan profile detect --force
          conan profile show default
      
      - name: Conan Create Package
        run: |
          conan create . --build=missing -o shared=False -o fips=False
        timeout-minutes: 25
      
      - name: Trigger openssl-tools Build
        if: success()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.repos.createDispatchEvent({
              owner: 'sparesparrow',
              repo: 'openssl-tools',
              event_type: 'openssl-build-complete',
              client_payload: {
                openssl_version: context.sha,
                build_status: 'success'
              }
            });
